### ISSUE TITLE
is_ajax() has been deprecated in the current release of WooCommerce (6.1.0)

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#1029]
is_ajax() has been deprecated in the current release of WooCommerce (6.1.0), however it is still in use in two locations within “Multivendor Marketplace Solution for WooCommerce”:
dc-woocommerce-multi-vendor\classes\class-wcmp-product.php (line 415)
dc-woocommerce-multi-vendor\classes\class-wcmp-order.php (line 493)

WP 5.8.3, WC 6.1.0
https://wc-marketplace.com/support-forum/topic/deprecated-is_ajax-is-deprecated-since-version-6-1-0-use-wp_doing_ajax-instead/#post-133263

**Comment by cool-raju** [comment]
already added
