### ISSUE TITLE
adding description through elementor in product page causing error

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#1034]
https://wordpress.org/support/topic/compatibility-with-the-elementor-2/#post-15283230

when adding a description in product page of any vendor using elementor it is causing error in the shop page of that vendor also.

Here is the video-

https://www.loom.com/share/9f24d9177722416caf98855fc23785db

**Comment by cool-raju** [comment]
@moumitahalder @aditidualcube cant reproduce this issue in my end

**Comment by cool-raju** [comment]
@aditidualcube if you are facing this on your end then share a complete video ASAP.
