### ISSUE TITLE
Order Export omitting orders with deleted products

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#1043]
If a vendor product has been Permanently Deleted from Woocommerce, those products are being omitted from the export. As a result, if an order a vendor had only had that 1 product, the orders aren’t included in the export.

To recreate this, you’ll want to:

1) Place a couple of orders with a product
2) Permanently delete that product from Woocommerce
3) Go back into Orders screen in the front end manager as a Vendor and export the Orders.

You’ll see that any order that had that deleted product on it is either removed from the “Items bought” column of the Export, or, if that was the only item on the order, the export does not include the order.

src : https://wc-marketplace.com/support-forum/topic/order-export-omitting-orders/#post-134081

**Comment by cool-raju** [comment]
use `add_filter('wcmp_order_export_if_product_exist', '__return_false');` this code to export order with deleted produts
