### ISSUE TITLE
Recaptcha version 2 not working for WCMp vendor contact widget

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#1053]
*To Recreate this*
1.Add WCMp Contact widget.
2.Add the Recaptcha script and secret key and click on save.

Error showing (see screenshot- 
![image](https://user-images.githubusercontent.com/90609843/156319315-b2536c1d-992e-49d4-940a-45dd214a83eb.png)

Expected flow- 
Recaptcha should display.

**Comment by moumitahalder** [comment]
@cool-raju the issue is not fixed.
