### ISSUE TITLE
Rest API issues- Updating a vendor- using (PUT) method

### ISSUE THREAD

**Issue by tan-hue** [wcmarketplace/dc-woocommerce-multi-vendor#1062]
1. testing through postman, the JSON code is throwing 401 error in postman dashboard, whereas the changes are shown for the particular vendor.
2. once the changes are made and reflected on the particular vendor (admin >> vendors) further changes cannit be made through the keyboard.

https://watch.screencastify.com/v/f1r9fK6XMS73UeUBUmim 
 
https://prnt.sc/X476f2UZhEe4

**Comment by cool-raju** [comment]
check this video
https://www.loom.com/share/56c8608251814c9eb786641fc24f9589

**Comment by tan-hue** [comment]
Hello,

I have been following the same process and was testing the REST API so far.
Expect this, all the codes were giving me proper results.



Thanks & Regards
Tandrima Chakraborty
9123086311
