### ISSUE TITLE
Share Coupon not working

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#1073]
Disable the option "Share Coupon Discount"

Current flow : 
Vendor A pays a 10% commission to the admin.
Customer buy products worth £100 with vendor A. Customer uses 50% discount so pays £50.
Current behavior: Vendor A receives a Commission of £50.
=======================================================================
Desired behavior: Vendor A receives a Commission of £90.

**Comment by cool-raju** [comment]
wcmp_admin_pay_commission_more_than_order_amount use this filter to pass commission price more than product price
