### ISSUE TITLE
Stop creating sub order for failed order

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#1086]
https://wc-marketplace.com/support-forum/topic/failed-orders-creating-commissions/#post-137429

**Comment by cool-raju** [comment]
add_filter('wcmp_create_order_commissions_as_per_statuses', function($status, $order_id) {
    $suborder = wc_get_order($order_id);
    if ($suborder && $suborder->get_status() == 'failed') {
        return false;
    }
    return true;
}, 10, 2);
