### ISSUE TITLE
WCMp Commission Calcutaion Error when product has multiple categories

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#111]
Recreate the Issue :
Assign  two different commission value in two categories :
![Screenshot](https://user-images.githubusercontent.com/28754174/66104509-67475180-e5d6-11e9-8004-ad939dc144b9.png)
![Screenshot](https://user-images.githubusercontent.com/28754174/66104616-c73df800-e5d6-11e9-8370-1689faf0f627.png)

Now, assign these two categories with your product : 
![Screenshot](https://user-images.githubusercontent.com/28754174/66104649-e9377a80-e5d6-11e9-894d-511ee3f44fe5.png)

Global Commission Value :+1: 
![download](https://user-images.githubusercontent.com/28754174/66104788-50edc580-e5d7-11e9-87bf-d098176d2c95.png)

Product Cost :
![Screenshot1](https://user-images.githubusercontent.com/28754174/66104830-67941c80-e5d7-11e9-92f7-5ad351cab8bb.png)

Resulted Commission: Commission will be calculated using global commission amount, rather than category wise

![download](https://user-images.githubusercontent.com/28754174/66104936-990ce800-e5d7-11e9-9c32-27cbf83d6802.png)

Expected Behaviour : 
If a product has multiple categories, then the highest commission should be calculated

**Comment by itzmekhokan** [comment]
@moumitahalder

**Comment by moumitahalder** [comment]
@itzmekhokan , this is fixed.

**Comment by itzmekhokan** [comment]
@moumitahalder okey LGTM.
