### ISSUE TITLE
Add rating under WCMp Admin Vendor Tab 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#129]
Let admin see the review of the vendor's under WCMp >> Vendor tab 

![Screenshot from 2019-09-12 18-19-24](https://user-images.githubusercontent.com/28754174/66806390-0a885700-ef45-11e9-8e03-7134133d5f0e.png)

**Comment by itzmekhokan** [comment]
What is the need of this column, Admin can easily view each vendor rating via "Quick View" icon.

**Comment by itzmekhokan** [comment]
@moumitahalder please explain a bit more for this requirements.

**Comment by itzmekhokan** [comment]
@moumitahalder I'm closing this issue, as I'm not getting a valid points from your end.

**Comment by moumitahalder** [comment]
@itzmekhokan, currently admin can only see the review of the vendor from their shop page. This section will let the admin see which vendor has low/high rating. This section is important because this lets the admin decide whether to continue with that vendor.

**Comment by itzmekhokan** [comment]
@moumitahalder, FYI this section is already there through which admin can see respective vendor rating via quick view ( eye icon ) toggle.
