### ISSUE TITLE
Vendor Registration form attachment issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#132]
- Goto WCMp >> Settigs >> Vendor and add Attachment field
- Make it not required 
- Now as a customer apply to become a vendor
- The attachment field becomes required and the error says ‘Please upload a valid file’ although that field is not required. 

![pls-upload-a-valid-file](https://user-images.githubusercontent.com/28754174/66910983-40086f80-f02d-11e9-9b47-054b430b338e.png)

- For non logged in user, there is no error.

**Comment by itzmekhokan** [comment]
@moumitahalder please double check the issue.
