### ISSUE TITLE
WPML compatibility with WC Marketplace

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#133]
Here is the doc : https://wpml.org/documentation/support/achieving-wpml-compatibility-for-your-themes-and-plugins/

**Comment by Matteo182** [comment]
Hi I have a multilingual site with WPML and in the product list in the seller's dadhboard I could see all the products of all languages in any language. So I looked in your code where the seller's product list is generated and I entered this in file : 
\classes\class-wcmp-ajax.php

to the row 1862

/* check if the product ID is the one of the current language in WPML */ 
                    if ( function_exists('icl_object_id') ) { // WPML activated
                        $correct_product_id = apply_filters( 'wpml_object_id',$product_single->ID , 'product', false, ICL_LANGUAGE_CODE );
                        if($correct_product_id != $product_single->ID){
                            continue; // skip the current loop and go to the next product
                        }
                    }

**Comment by Matteo182** [comment]
Hi I have a multilingual site with WPML and in the product list in the seller's dadhboard I could see all the products of all languages in any language. So I looked in your code where the seller's product list is generated and I entered this in file :
\classes\class-wcmp-ajax.php

to the row 1862

/* check if the product ID is the one of the current language in WPML */
if ( function_exists('icl_object_id') ) { // WPML activated
$correct_product_id = apply_filters( 'wpml_object_id',$product_single->ID , 'product', false, ICL_LANGUAGE_CODE );
if($correct_product_id != $product_single->ID){
continue; // skip the current loop and go to the next product
}
}

**Comment by moumitahalder** [comment]
Hi @Matteo182, we didn't receive any pull request. 

Kindly follow this doc, to add your modification: https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

**Comment by Matteo182** [comment]
Hi @moumitahalder ,  now i made another pull request changing the brach name in Wpml compatibility #221, this is the message : "	Matteo182 wants to merge 3 commits into wcmarketplace:master from Matteo182:WPML_compatibility" I followed the instructions, can you tell me if it is correct? do you see the ever request?
