### ISSUE TITLE
WCMp Transaction ID and Banking Override Page Issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#135]
WCMp Transaction ID and Banking Override Page Issue

To recreate the issue :
Case 1: 
- The payment mode selected by the vendor is Bank Transfer
- They have asked for a withdrawal
- When admin marked the commission as Paid, from the commission details page
![Screenshot](https://user-images.githubusercontent.com/28754174/67083818-7c68d680-f1b9-11e9-897e-c51f97aa62a0.png)

![Screenshot (1)](https://user-images.githubusercontent.com/28754174/67083969-b9cd6400-f1b9-11e9-9017-bbc9eaab1d8c.png)

- In this case, go to Banking Overview page you will not find that Withdrawal saved (new issue).
![Screenshot (2)](https://user-images.githubusercontent.com/28754174/67083977-bc2fbe00-f1b9-11e9-9be9-e598f9834517.png)

Case 2 :
- The payment mode selected by the vendor is Bank Transfer
- They have asked for a withdrawal
-  Mark as Paid a commission from the general main Commission table using the Bulk actions 
![Screenshot (3)](https://user-images.githubusercontent.com/28754174/67084044-da95b980-f1b9-11e9-965d-00b8196b3320.png)

![Screenshot (5)](https://user-images.githubusercontent.com/28754174/67084120-f8631e80-f1b9-11e9-92bf-7b378b435e3f.png)

- goto Withdrawal History (vendor dashboard) 2 transactions for that same commission

![Screenshot (5)](https://user-images.githubusercontent.com/28754174/67084134-fdc06900-f1b9-11e9-89d1-93a174a6c768.png)

- go to Banking Overview, one in “Processing” status, and the other one in “Completed” status. 
If you  now you will see the Withdrawal saved in the table because of the Completed transaction (commission) appeared in Withdrawal History.

![Screenshot (6)](https://user-images.githubusercontent.com/28754174/67084160-0b75ee80-f1ba-11e9-91ec-5e39473c4ddd.png)

**Comment by itzmekhokan** [comment]
@moumitahalder there is an issue in case 1 but please double check with case 2, may be it was due to double triggered action.

**Comment by moumitahalder** [comment]
@itzmekhokan , I checked the case 1. Now banking overview is showing the transaction, however it is showing the data twice. 

![Screenshot (1)](https://user-images.githubusercontent.com/28754174/67260731-8a20a380-f4ba-11e9-90fb-538902714077.png)

![Screenshot (2)](https://user-images.githubusercontent.com/28754174/67260743-a7ee0880-f4ba-11e9-9f7b-f4d0076d2beb.png)

**Comment by moumitahalder** [comment]
For Case 2 :

I checked again, it is still showing 2 transactions for that same commission under Withdrawal History (vendor dashboard)

**Comment by itzmekhokan** [comment]
@moumitahalder, please check with default theme and basic needed plugins only.

**Comment by moumitahalder** [comment]
@itzmekhokan, yes did the testing using Twenty Seventeen and kept only WooCommerce and WCMp active. Still faced this issue : https://www.loom.com/share/5df17806925e4bba92acd5fc5a06247b

**Comment by itzmekhokan** [comment]
@moumitahalder again I want to tell you, please do a test properly and think the process before going to other steps. And double check your attached video carefully and also apply your brain, you are actually created double transactions.

**Comment by moumitahalder** [comment]
@itzmekhokan Enlight me what are you referring here as a double transaction? 
All I did is asked for a withdrawal from the vendor end.
Because vendor payment mode is Bank Transfer, hence admin has to mark the commission as paid manually. 

I don't see any double transaction here.
Please note, this is only happening when the vendor's payment mode is Bank Transfer.
