### ISSUE TITLE
More Offer tab for External Product

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#136]
- Add a external product from admin / vendor end
- Now using SPMV flow, add the same product from vendor or admin end
- Now view the product in the single product page
- Goto More Offer tab
- You will see the "But On this site" option is not there 

![Screenshot (7)](https://user-images.githubusercontent.com/28754174/67093942-53077500-f1d0-11e9-9a7d-27e4b80f43e9.png)

**Comment by itzmekhokan** [comment]
@moumitahalder

**Comment by moumitahalder** [comment]
@itzmekhokan It is fixed.
