### ISSUE TITLE
Export the list of bank transfers

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#143]
Could you add a feature to export the list of bank transfers details (i.e. how much money to be paid to a vendor in a selected time and corresponding duration) so admin can have a list of bank transfers

**Comment by itzmekhokan** [comment]
@moumitahalder needs some details planning to execute this.

**Comment by moumitahalder** [comment]
@itzmekhokan will provide you a fully functional flow.

**Comment by moumitahalder** [comment]
When admin pays the vendor via bank transfer, currently they have to check how much to pay from the commission tab and then they go to the vendor's payment tab to get the bank account details. 

Also, if we can let the admin have a csv, where they can see all the unpaid commissions and corresponding commission amount and bank details. This will let help manage this whole process easily. 

This CSV should contain these details (if possible):
- Vendor Name
- Order ID
- Commission ID 
- Total Earning 
- Total Earning Per vendor 
- Bank Details

**Comment by itzmekhokan** [comment]
@moumitahalder thanks for your explanation.

**Comment by itzmekhokan** [comment]
@moumitahalder needs fresh testing
