### ISSUE TITLE
String supoort in Vendor banking overriew

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#145]
- String Support : Commission generated for Order
![Screenshot](https://user-images.githubusercontent.com/28754174/67620042-33033180-f820-11e9-8d62-f09e5a8ab386.png)

- Not reflecting under Vendor Banking 
![Screenshot1](https://user-images.githubusercontent.com/28754174/67620063-65149380-f820-11e9-975b-a5f74087819c.png)

**Comment by itzmekhokan** [comment]
@moumitahalder String translations are already there. if any translations available then we are storing the respective reference information ( translated ) into our table. So make sure first the table row saving your translated string as well, because we are showing all data from table.

**Comment by moumitahalder** [comment]
@itzmekhokan, thanks for the update. The table was not updated.
