### ISSUE TITLE
Failed order leaves suborder Pending payment

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#146]
- If the main order failed, then the suborder remained pending. 
-  Suborders in ‘pending’ status show up as sales in the reports too. 

https://www.loom.com/share/1eeec3be458c4882a1caf987ef2eb5d5

Source : https://wc-marketplace.com/support-forum/topic/failed-order-leaves-suborder-pending-payment/

**Comment by itzmekhokan** [comment]
@moumitahalder Can you please test the above with updated master once. Do let me know your feedback.

**Comment by moumitahalder** [comment]
@itzmekhokan , this issue is fixed.
