### ISSUE TITLE
Add Product option from top menu 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#150]
To reproduce this issue - When Single Product Multiple Vendors is enabled and Disable Advanced Marketplace Product Listing is enabled, on clicking on the “Add Product” option from the top menu, vendors can select a category. 

https://www.loom.com/share/63bbcc1dc0c34d3cb4a3f2e991d06b31

**Comment by Susmita-dualcube** [comment]
To reproduce the issue - When "Disable Advance Marketplace Product Listing" is enabled and "Single Product Multiple Vendor" option is disabled, clicking on Add Product option from All Product tab, vendors can select category. 

[https://www.loom.com/share/10b129513d364180961a8c47d4a3ca7c ](url)
