### ISSUE TITLE
Customer view review of vendor

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#151]
- when a user cannot add a review (Only buyers, purchased from the vendor can rate. is selected only) then he cannot see the reviews of the vendor at all.

https://www.loom.com/share/811454b20dfd494cb71c9441c0c7d9ed

Expected Behavior: Any logged in /non-logged in user should be able to view the review.

**Comment by itzmekhokan** [comment]
@moumitahalder meaningless issue.
