### ISSUE TITLE
Missing $parameter 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#154]
add in file ../admin/class-wcmp-settings-vendors.php parameter $vendor_obj

line 624
`$WCMp->wcmp_wp_fields->dc_generate_form_field(apply_filters(“settings_{$this->tab}_personal_tab_options”, $personal_tab_options, $vendor_obj));`

line 630
`$WCMp->wcmp_wp_fields->dc_generate_form_field(apply_filters(“settings_{$this->tab}_store_tab_options”, $store_tab_options, $vendor_obj));`

line 634
`$WCMp->wcmp_wp_fields->dc_generate_form_field(apply_filters(“settings_{$this->tab}_social_tab_options”, $social_tab_options, $vendor_obj));`

line 638
`$WCMp->wcmp_wp_fields->dc_generate_form_field(apply_filters(“settings_{$this->tab}_payment_tab_options”, $payment_tab_options, $vendor_obj));`

This parameter is necessary to add custom fields in Admin > WCMp > Vendors > [item] > [Tab]

source : https://wc-marketplace.com/support-forum/topic/please-add-parameter-in-admin-class-wcmp-settings-vendors-php/#post-78788

**Comment by itzmekhokan** [comment]
Fix Added in v3.4.5.
