### ISSUE TITLE
Vendors can select category from Add Product option of All Product, even if Disable Advanced Marketplace Product Listing option is enabled.

### ISSUE THREAD

**Issue by Susmita-dualcube** [wcmarketplace/dc-woocommerce-multi-vendor#155]
To reproduce the issue - When "Disable Advance Marketplace Product Listing" is enabled and "Single Product Multiple Vendor" option is disabled, clicking on Add Product option from All Product tab, vendors can select category.

https://www.loom.com/share/10b129513d364180961a8c47d4a3ca7c

Steps to reproduce the behaviour - Enable “Disable Advance Marketplace Product Listing” option and disable “Single Product Multiple Vendor Option” via WCMp >> Settings >> Payment. 

Click on Add Product option from All Products tab in the vendor’s dashboard. You will be redirected to the category selection page.

![Screenshot (4)](https://user-images.githubusercontent.com/57519087/68837083-d5a52680-06e1-11ea-85e9-3fe10124829b.png)

Expected behaviour - When “Disable Advance Marketplace Product Listing” option will be enabled, on clicking on “Add Product” option from “All Products” tab, vendor should be directed to the “Add Product Details/Edit Product” page.

**Comment by tiligadis** [comment]
Since this is the first step when "Disable Advance Marketplace Product Listing" it's a mistake to write 
"Step 2 of 2: Add Product Details"
should be single "Add Product Details"
So remove the "Step 2 of 2:"
