### ISSUE TITLE
change more vendors button

### ISSUE THREAD

**Issue by sirdash** [wcmarketplace/dc-woocommerce-multi-vendor#156]
hi
i want change "more vendors" button locations in woocommerce_single_product_summary but i can't .
please help 
thanks

**Comment by itzmekhokan** [comment]
@sirdash we are also using `woocommerce_single_product_summary` hook to show "More vendors" button at priority 60. So, can definately reposition it. Here is the follows snippet - 

```
add_action( 'wcmp_init', 'modify_wcmp_products' );
function modify_wcmp_products() {
    global $WCMp;
    remove_action('woocommerce_single_product_summary', array( $WCMp->product, 'product_single_product_multivendor_tab_link' ), 60 );
    add_action('woocommerce_single_product_summary', array( $WCMp->product, 'product_single_product_multivendor_tab_link' ), 21 );
}
```

**Comment by sirdash** [comment]
Problem solved, Thanks
