### ISSUE TITLE
Vendors unable to remove the existing category of a product on editing, keeping “Disable Marketplace Product Listing” option unchecked.

### ISSUE THREAD

**Issue by Susmita-dualcube** [wcmarketplace/dc-woocommerce-multi-vendor#157]
To reproduce the issue - When vendors try to edit a product’s category of an already existing product, the previously assigned categories for that product cannot be removed. Only new categories can be added along with the existing one’s.

https://www.loom.com/share/57a245b84e2d4e668760959555d28c26 

Steps to reproduce the behaviour - Uncheck “Disable Advance Marketplace Product Listing” and try to edit a product to change the pre-existing category. Uncheck the pre-existing category and assign a different category. The old category still exists. The new category gets added with the old one. 

![pic2](https://user-images.githubusercontent.com/57519087/68993704-1303e280-08a1-11ea-8752-2483d684e390.png)

Expected behaviour - When a product will be edited to change the pre-existing category to a new one keeping “Disable Advance Marketplace Product Listing” option unchecked, the pre-existing category should be removed.

**Comment by paul-view** [comment]
This does not work the way you say here.
If I uncheck the 'Disable advance marketplace product listing flows like popular ecommerce site.'
It changes to only be able to select 1 category only
![image](https://user-images.githubusercontent.com/37223786/69476219-1fbb9580-0dcf-11ea-9ddb-d6b68427da29.png)

see here

![image](https://user-images.githubusercontent.com/37223786/69476227-306c0b80-0dcf-11ea-94e3-e991ad373c93.png)

I can give you admin access

**Comment by moumitahalder** [comment]
@paul-view, this is not an issue. Let me help you out with our default flow. 
- As you are using Adance Product listing flow, hence a product will have one parent category and one corresponding subcategory. 
- Hence at the time of changing the subcategory, you can only select one subcategory.

**Comment by paul-view** [comment]
It does not matter what way this is done, it is not correct

Using “Disable Advance Marketplace Product Listing” checked means only 1 category can be used

Without it, multiple categories can be used

BUT THE USER CANNOT REDUCE THE CATEGORY SELECTION, ONLY ADD A CATEGORY

**Comment by itzmekhokan** [comment]
@moumitahalder @paul-view Advance Marketplace Product Listing is a well known e-commerce listing where user cannot change some unique features like categories, GTIN etc. once they chosen these already at the time of product listing. By disabing it you can override the process.

**Comment by paul-view** [comment]
Can you make your answers clearer

If we can disable then tell us how
Also would this have any knock-on affect

It seems that this is something that should be easy, as it is with other processes/stores and is a real issue with WCMP

**Comment by itzmekhokan** [comment]
@paul-view the respective setting does as follows-
Checked : if settings is checked/set, you can add or modify product categories.
Unchecked : if settings is unchecked/unset means it has the default settings then you will able to add or modify categories only once at the time of its initial product listing.
I hope it will make you clear.

**Comment by paul-view** [comment]
So still the system will NOT allow the amending of categories after first
setting which is a bug.

Scenario

If admins decide to add or remove categories, you plug in will fail

**Comment by moumitahalder** [comment]
@paul-view we can't reproduce the issue as you said. Make sure that you are using the updated plugin version. 
If the problem still exists please contact through our support forums

**Comment by paul-view** [comment]
You won't be able to reproduce the issue as you need to be logged in as a
Vendor.
I thought when I first posted this, you recognised the problem and saw this
as an error in the code

**Comment by moumitahalder** [comment]
@paul-view , did you tested the flow with the current version of WC Marketplace ?
