### ISSUE TITLE
Change category of a product

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#158]
**Describe the bug**
When a vendor is unassigning any category, still the category is associated with that product. 

**To Reproduce**
1. Enable the 'Disable Advance Marketplace Product Listing' via WCMp >> Settings >> General
2. Go to 'Vendor Product list page'
3. Click on 'Edit button of an existing product'
4. Now, goto the category list section. 
5. Unassign any category
6. Save the product
7. You can see the category is still associated with the product. 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/28754174/69123128-93eff380-0ac6-11ea-8760-cd1a144fb96e.png)

https://www.loom.com/share/29440295b71c4dc38bf8349752f4842e

**Expected behavior**
When a vendor is removing any category, it should be removed.

**Comment by paul-view** [comment]
This reproduces the issue
How can we fix it?

**Comment by cool-raju** [comment]
same as issue no #157 .
