### ISSUE TITLE
Disable Add tag filter issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#160]
**Describe the bug**
Disable add tag filter is not working : add_filter('wcmp_vendor_can_add_product_tag', '__return_false');

To Reproduce
- Add this filter at the function.php of the current active theme 
add_filter('wcmp_vendor_can_add_product_tag', '__return_false');

- Go to Vendor Dashboard and add a product
- You can see the vendor is still able to add the tag

![Screenshot](https://user-images.githubusercontent.com/28754174/69137494-e5a67700-0ae2-11ea-9f50-c79c638b5b90.png)

**Comment by angelomagrone84** [comment]
add_filter('wcmp_vendor_can_add_product_tag', '__return_false'); works fine!

Prevents the vendor from writing new tags from the dashboard. Vendor can select preloaded tags.

**Comment by itzmekhokan** [comment]
@moumitahalder Invalid issue.
