### ISSUE TITLE
Deleted commission stays on Banking Override

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#162]
Recreate the issue :
- Delete an order from admin end
- Delete the commission also
![download](https://user-images.githubusercontent.com/28754174/69328862-03f0ac00-0c76-11ea-8ec7-4b0068d622c1.png)

- Now goto vendor's banking overview section, the order will be there. 
![download1](https://user-images.githubusercontent.com/28754174/69328867-06eb9c80-0c76-11ea-9429-7253d7ae22ee.png)

**Comment by dekaepta** [comment]
It's not only this problem.
I cannot answer to the other thread i have open here (your forum need fix!)
https://wc-marketplace.com/support-forum/topic/banking-overview-withdrawals-not-shown/

**I **made a fresh install** with only WC-Marektplace and Woo**
and when pay commission to a vendor you cannot see it in banking-overview
https://we.tl/t-Obq6rKtISS

**Comment by itzmekhokan** [comment]
@moumitahalder this is not a issue. Banking ledger is a one time process of every respective action. And that is written in as in overview details by current action which are displayed as every vendor past activities.
There is no logic to change the process.

**Comment by moumitahalder** [comment]
@itzmekhokan , you are right. That this is a one-time process. 
However, as the commission is deleted, hence it should reflect on the banking overview too. 
Can't we add a new row, to update the banking ledger section?
