### ISSUE TITLE
Not able to crop images 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#170]
* Reproduce this issue :
- Login as vendor
- Goto Vendor Dashboard >> Shop Settings >> Storefront
- Upload any image for shop banner/shop logo.
- At the time of editing the image, you will get this error : 
![Screenshot from 2019-11-27 12-59-05](https://user-images.githubusercontent.com/28754174/69702777-f9bb2b80-1115-11ea-86db-6564f0d28d63.png)

**Comment by itzmekhokan** [comment]
@moumitahalder do a fresh test with v3.4.6

**Comment by moumitahalder** [comment]
@itzmekhokan Did a fresh test with WCMp 3.4.6, the issue is resolved.
