### ISSUE TITLE
WCMp sub order issue with REST API

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#176]
- Connect WC through the WC API to “Create Order” for a product linked to a vendor
- This will not create the sub-order automatically for the vendor account and therefore not showing on the vendor dashboard.

Source : https://wc-marketplace.com/support-forum/topic/wc-rest-api-create-order-not-creating-suborder-for-wcmp-vendor/#post-84520

**Comment by hakangoker** [comment]
How long you guys think this can be repaired? Is there time frame you can give us?

**Comment by gauravbordoloi** [comment]
Hello, I just tried to create an order with the following body :

`{
	"status": "pending",
	"currency": "INR",
	"customer_id": 0,
	"customer_note": "Please pack the items with care. Last time, my butter got melted.",
	"billing": {
		"first_name":"Dharma",
		"last_name": "Bordoloi",
		"address_1": "House 24, Gotanagar, Tetilia",
		"address_2": "Near Heritage School",
		"city": "Guwahati",
		"state": "Assam",
		"postcode":"781011",
		"country":"IN",
		"email":"dharma514@gmail.com",
		"phone":"9101750676"
	},
	"shipping": {
		"first_name":"Dharma",
		"last_name": "Bordoloi",
		"address_1": "House 24, Gotanagar, Tetilia",
		"address_2": "Near Heritage School",
		"city": "Guwahati",
		"state": "Assam",
		"postcode":"781011",
		"country":"IN"
	},
	"payment_method": "paytm",
	"payment_method_title": "Paytm",
	"meta_data": [
		{
			"key":"has_wcmp_sub_order",
			"value":2
		}
	],
	"line_items": [
		{
			"product_id":2850,
			"variation_id":2856,
			"quantity":3
		},	
		{
			"product_id":4777,
			"quantity":2
		}	
	]
}`

But suborder is not being created. What mistake am I doing?
