### ISSUE TITLE
Where are the source assets

### ISSUE THREAD

**Issue by jsakas** [wcmarketplace/dc-woocommerce-multi-vendor#186]
Hi there, we would like to develop and customize the features of this plugin by compiling the frontend source manually.

For example, we would like to compile the sass in order to customize the current color schemes as the 4 provided do not match our brand.

Is there any plan to upload the source files into this repository? You have the package json and all the build scripts, but actual source files seem to be missing.

**Comment by itzmekhokan** [comment]
@jsakas currently we don't provide such flexibility to add your own color pallets. To do so you have to add your custom styling for your respective style template.
We are planning to add such features very soon.

**Comment by jsakas** [comment]
Hi @itzmekhokan, thanks for the reply!

We would really like to do some heavy customization of the frontend by compiling the sass using the grunt scripts that are included, keeping a fork of this repo. 

You can probably imagine that if we modified the css directly, it would be very difficult to keep a fork up-to-date.

As an example, WooCommerce includes all of their scss files on GitHub for their core free plugin. It would be awesome if WCMp did the same for those developers wanting to customize the look and feel of the dashboard!

**Comment by itzmekhokan** [comment]
@jsakas yes that's why I told you before that we don't have that much flexibility right now ( sass modules ).
We are also planning to do so. And thanks for your suggestions. We will surely keep you posted.

**Comment by jsakas** [comment]
@itzmekhokan so what is this for? https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/blob/master/Gruntfile.js#L77

Or are you writing CSS manually and this is unused boilerplate grunt configuration?

**Comment by itzmekhokan** [comment]
@jsakas there are some limited sass files as you can see. Currently WCMp dashboard color pallets styling mixed up with frontend dashboard css. We need to make it different ( for color pallets ).

**Comment by jsakas** [comment]
I'm sorry I don't see the sass files you mention anywhere in this repository. I understand that palette customization is on your roadmap but thats not necessarily what I am asking. :)

It would be great if you would commit the source for these css files, for those of us who want to build the frontend assets manually. For instance this file: https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/blob/master/assets/frontend/css/vendor_dashboard.css

It's very clearly a compiled sass file... yet the source file is no where to be found.

**Comment by jsakas** [comment]
@itzmekhokan any update on the location of the sass file that generates `vendor_dashboard.css` ?

**Comment by itzmekhokan** [comment]
@jsakas we updated sass files in version 3.4.8.
