### ISSUE TITLE
Partially refunded order’s commission when marked back as paid, does not reflects in the Banking Overview and Withdrawal section of the vendor’s dashboard. 

### ISSUE THREAD

**Issue by Susmita-dualcube** [wcmarketplace/dc-woocommerce-multi-vendor#188]
**To Reproduce the issue**
- Create a new vendor
- Place an order in the site
- You can see that the amount is added under Credit Tab
- Now, mark the commission as Paid. 
- You can check the Debit row is not added

https://www.loom.com/share/5405f0c840eb44cca1732105ec328514

- So basically, if the total commission amount due to the vendor is 0, the banking overview is not deducting the last amount, which will make the due amount 0.

**Comment by moumitahalder** [comment]
@itzmekhokan Issue updated with proper description to reproduce. Please check again.

**Comment by itzmekhokan** [comment]
@moumitahalder please do double check before post and do all the step for a new vendor before placing withdrawal.
