### ISSUE TITLE
Product name link in Enquiry Details section of Catalog Enquiry tab redirects to add product page. 

### ISSUE THREAD

**Issue by Susmita-dualcube** [wcmarketplace/dc-woocommerce-multi-vendor#190]
To describe the issue - The product name link in the Enquiry Details section of Catalog Enquiry tab redirects to add product page. 

https://www.loom.com/share/a01531e8f9064e63aabe5e4b811344f5 

Steps to reproduce the behaviour -  (i) Add a product to the enquiry cart from the shop page.
                                                         (ii) Check the enquiry details of the product from the vendor's 
                                                              dashboard via Catalog Enquiry >> Enquiry Details. 
                                                         (iii) Click on the product name link from the "Product" column of 
                                                               the Enquiry Details section. 
                                                         (iv) The product name link will redirect to the add product page 
                                                               instead of displaying the product details. 
                                                          
![FireShot Capture 281 - Screenshot by Lightshot - prnt sc](https://user-images.githubusercontent.com/57519087/70986529-15e23500-20e4-11ea-94ff-0ad1ef6fb566.png)

Expected behaviour - The product name link in the Enquiry Details section of Catalog Enquiry tab 
                                    should display the product details.

**Comment by itzmekhokan** [comment]
@Susmita-dualcube the above issue is not related to core. The fix need to be done in its add-ons ( Catalog Enquiry ).
