### ISSUE TITLE
Let admin remove pending payment data from withdrawable balance 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#195]
**Current Flow:-**
- Currently, if an order is placed by a customer is waiting for payment, i.e. order status will be set to "Pending Payment".

- Then in Withdrawl balance will show the pending payment amount, but vendor can't withdraw this (as a vendor can only withdraw those orders, that is either processing or completed)

**Expected Behaviour:-**
- If an order is yet to be paid by the customer, then a vendor cannot withdraw the amount
- So, the withdrawable balance should show the order that has been paid by the customer i.e. processing and completed

**Comment by moumitahalder** [comment]
@itzmekhokan, if an order is not paid yet by the customer, then logically the vendor should not be able to receive their commission via withdrawing the order amount.

**Comment by moumitahalder** [comment]
@itzmekhokan, if an order is not paid yet by the customer, then vendors can't withdraw commission as per our flow.

Now some of our users want to deduct the On-hold/Pending payment amount from the withdrawable balance too: https://prnt.sc/qkok49

So,  can you add a filter there, so the user can use that to add their modification?

**Comment by admin242424** [comment]
This should not be closed:

– Amount still shows in the withdrawable balance for pending payment orders.
– Pending payment orders are still showing in the payouts list (greyed out).
– Dashboard widget shows pending payment orders in revenue and unique purchases**
– Stats/Reports include pending payment orders**

**These are serious issues. Vendors are doing their taxes now and using reports to justify their earnings, but they’ve not actually earned it all. Please help fix this ASAP.
