### ISSUE TITLE
Create an order for each seller in the cart

### ISSUE THREAD

**Issue by lbensaad** [wcmarketplace/dc-woocommerce-multi-vendor#20]
If a buyer adds many products from different sellers then we should split the order into multiple orders, one for each seller. For example if a customer creates order 60 from two sellers, we create order 61 that has products from seller1 and order 62 that has products from seller2, orders 61 and 62 will have their post_parent set to 60 and order 60 will be empty. 
Like this, it will be easier for management, every seller manages his own order. For example, each seller can change the order status separately.

**Comment by subrata-dc** [comment]
@lbensaad 
We are planing to create sub order of main order in upcoming updates.

**Comment by lbensaad** [comment]
Thanks @subrata-dc , but shouldn't be this issue left open till the feature is added, or if you can give an estimate when it will be implemented?

**Comment by subrata-dc** [comment]
@lbensaad  
We will open a ticket soon with details features and implementation process. Please stay with us, we will definitely tag you in that ticket.
Thanks

**Comment by Matthieuhal** [comment]
This will should be useful to sync Woocommerce/WCMP with external CRM like bitrix24. Any ETA ?

**Comment by sushobhan-pal** [comment]
@Sophivorus split order feature is already accepted by our development team. We haven't started working on this but will do soon. The flow proposed by @lbensaad is our first preference but we are still looking if there is a better alternative to this. 
@Matthieuhal can't commit a fixed ETA but hopefully, by August we will be able to bring this feature. We have our development calendar full for the upcoming two months.
If you guys want to contribute to the development process, you are more than welcome :)
Whatever happen we will keep you posted.

**Comment by Sophivorus** [comment]
Yes! I'd very much like to participate in the development process. Do you use SVN (https://wordpress.org/plugins/dc-woocommerce-multi-vendor/#developers)? Or where should I head to?

**Comment by sushobhan-pal** [comment]
Hi @Sophivorus ,
Thanks for showing your interest.
Yes, you can send us your pull requests through here.

**Comment by Matthieuhal** [comment]
Thanks: "by August" is quite an ETA ... with that info i can make my decision. Thanks a lot.

By the way: I post a comment on this plugin on Envato invite developer to contact you to make his plugin WCMP compatible ... managing to do that would mean that WCMP would get integration with Bitrix24 (bitrix24.com) one of the best and cheapest CRM-all-in-one (I am a user and run my company with Bitrix . I recommend to all of you).

https://codecanyon.net/item/woocommerce-bitrix24-crm-integration/21320217/comments

**Comment by sushobhan-pal** [comment]
@Matthieuhal we might be able to bring this feature before that. But as we have our hands full with other milestones so kept some additional time buffer.
I pass your message to our team so if the plugin author (you mentioned) contacted us, our team will do our best to help him/her. Thanks!

**Comment by moumitahalder** [comment]
@Matthieuhal, We have released the beta version of our split order module. This document might help you out further – https://wc-marketplace.com/latest-release/

You can download that from here – https://github.com/dualcube/dc-woocommerce-multi-vendor/archive/devs.zip

**Please note, This WCMp Split Order ( Beta – 1 ) is in active development and beta release for WCMp Split order next major version.For better debugging, it’s also recommended you add define( ‘SCRIPT_DEBUG’, true ); to your wp-config. It is recommended not to use this version in live site.**

You can test the plugin in this demo site – http://demo.dualcube.com/wordpress/wp1018/my-account/
