### ISSUE TITLE
Wrong "Add Product" link

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#209]
**Recreate this issue**
- Disable SPMV option
- Enable the Disable Advance Marketplace Product Listing option 

Goto Vendor Dashboard
- Under "Product Stats" widget, you will get the Add Product option
- This link still directs the vendor to the "Edit Product"
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28754174/72876402-6d477680-3d1c-11ea-9c28-3a6be73bd514.gif)

**Comment by jenessawhite** [comment]
hello @itzmekhokan  & @moumitahalder. I have recently downloaded and installed v3.4.9 and still get the edit product link instead of an add product link
