### ISSUE TITLE
Query Optimization

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#231]
When a vendor with more than 10,000 products is adding a coupon, it is crashing the site.

**Comment by Matthieuhal** [comment]
Another aspect of Cupom management:
The coupons always need the vendor to define the whole range of products.
We understand that this is the way WVMp make cupon compatible with Multisellers.
Never theless it causes some trouble:
1/ As pointed, vendor attaching thousands of products may cause crash
2/ If Vendor create some new product after having creted the coupon, the coupoin will not be aplicable for those new product until vendor edit and update Coupon product list.

This can be an big issue on large sites.


Let's say a seller create de 5% discount.
