### ISSUE TITLE
String Support Missing for tooltip

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#237]
In add product >> downloadable.
The following translations do not work:

**– Leave blank for unlimited re-downloads.**
https://prnt.sc/ra4hr9

**– Enter the number of days before a download link expires, or leave blank.**
https://prnt.sc/ra4i2l

**Comment by itzmekhokan** [comment]
@moumitahalder the above strings are not related to WCMp. Those strings support are coming from different plugins subscription and bundle products, so strings translation can be achieve by their locale translations. Please double check and close the issue.

**Comment by moumitahalder** [comment]
@itzmekhokan, if you are selling downloadable products, then you can see the fields, like woocommerce :

https://www.loom.com/share/7c500ec8f95f44549d09c116d45b74a9

**Comment by itzmekhokan** [comment]
@moumitahalder those strings are coming from woocommerce.
