### ISSUE TITLE
Rest api remove user data on vendor update

### ISSUE THREAD

**Issue by Zacad** [wcmarketplace/dc-woocommerce-multi-vendor#250]
In vendor update method you are updating all user fields without checking if these fields are actually set in request.
![image](https://user-images.githubusercontent.com/3125932/76731620-209d7c00-675e-11ea-92a8-034b102eff38.png)

Is this desired situation? It can lead to unexpected behaviour when user try update only some vendor field and he will lose all user data like first name, last name, email and so on, as he only put field he wants to update in request

**Comment by cool-raju** [comment]
Hi @Zacad  we have already updated this in our 3.5 version. Can you please check and kindly keep us posted.
