### ISSUE TITLE
Create product search in vendor's shop page 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#282]
- create a widget that will search the product inside the vendor's shop page. 

abhi is working on this

**Comment by nikhilbhoyar** [comment]
May I know update for it !
Is this enhancement added in module ?

**Comment by nikhilbhoyar** [comment]
Any update ?

**Comment by nikhilbhoyar** [comment]
May I know update for it !
Is this enhancement added in module ?

**Comment by cool-raju** [comment]
Hi @nikhilbhoyar 
We have already updated the code here https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/issues/327. You can use this for testing purposes. If everything is right then we will update it in our next version.

**Comment by nikhilbhoyar** [comment]
@cool-raju @moumitahalder 
Can you please share code snippet to add this functionality.

**Comment by nikhilbhoyar** [comment]
@cool-raju @moumitahalder
Can you please share code snippet to add this functionality.

**Comment by moumitahalder** [comment]
@nikhilbhoyar this is already added in our latest update.
