### ISSUE TITLE
Let customer search vendor as per vendor's shipping zone

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#284]
- Let customer search vendor as per vendor's shipping zone in the vendor list
- enhance the shortcode parameter so admin can show vendor as per specific location

**Currently, we let the customer search vendors via the address field (https://prnt.sc/sd0xop). This address fetched the vendor’s location
> Enhancement: Along with the vendor’s location, fetch the vendor’s shipping zones too. 

This way vendors can be located as per the delivery zones too.** 

src : https://wc-marketplace.com/support-forum/topic/vendorlist-by-cities/
https://wc-marketplace.com/support-forum/topic/return-vendors-list/#post-94235

**Comment by adamholden1212** [comment]
Hi.

Has this feature been implemented? 
I would like to be able to search and display vendors based on their shipping locations.

Please provide any updates on this. Thank you
