### ISSUE TITLE
WCMp Report 3.5

### ISSUE THREAD

**Issue by sumit-singh-hash** [wcmarketplace/dc-woocommerce-multi-vendor#307]
From version 3.5, we will show Report in our own tab, instead of WooCommerces. 
Also, this will have the **Overview tab, vendor, product, banking overview per vendor**. 

https://www.loom.com/share/26e976e1282f43ceba6cf4793609a7f3

The flow will be :
Clicking on WCMp >> Report, it will open the Report Overview tab.

**Comment by moumitahalder** [comment]
Warning: include(1): failed to open stream: No such file or directory in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-307/admin/class-wcmp-settings-reports.php on line 118

Warning: include(): Failed opening '1' for inclusion (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-307/admin/class-wcmp-settings-reports.php on line 118
