### ISSUE TITLE
Add vendor search product in their shop

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#327]
- Create a widget for Vendor Shop
- This widget will search that vendor's product

**Comment by nikhilbhoyar** [comment]
Any update on this functionality ?

**Comment by nikhilbhoyar** [comment]
Any update on this functionality ?
where customer can search Vendor's Product in his SHOP Page.

**Comment by moumitahalder** [comment]
This is already fixed in our latest update. 

Kindly update the plugin and check.
