### ISSUE TITLE
WooCommerce REST API not showing parent orders

### ISSUE THREAD

**Issue by gauravbordoloi** [wcmarketplace/dc-woocommerce-multi-vendor#330]
I am making an api call to https://homedrop.in/wp-json/wc/v3/orders but it is never returning any parent order ( order with parent_id=0 ). It is only returning sub orders.

**Comment by cool-raju** [comment]
Hi @gauravbordoloi ,
This is woocommerce rest. And suborder is also an order like parent order.we are not getting any issue. please check this video https://www.loom.com/share/27e7216295584bf2b335df702f9bca1f of order response
