### ISSUE TITLE
Commission type flexibility 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#336]
possible to Charge Fixed Amount to some specific vendor/product per Transaction/per Unit?
src : https://wc-marketplace.com/support-forum/topic/commission-type-vendor-wise/

**Comment by nikhilbhoyar** [comment]
Any update on it ?

**Comment by nikhilbhoyar** [comment]
Any update on it ?

**Comment by cool-raju** [comment]
commission per product price added
