### ISSUE TITLE
Vendors access- Repeated action

### ISSUE THREAD

**Issue by mlc0092** [wcmarketplace/dc-woocommerce-multi-vendor#349]
I noticed that when one vendors wants to log in, after writing email and password and summit to login the web page refresh to the same login page again. Then if pressed again login, with or without writing username and password, the page refreshes and goes to the vendor dashboard. I thought that was fault of using cache plugins but when I try to do it with client count and it goes to the client dashboard at the first attempt.

**Comment by moumitahalder** [comment]
Hi @mlc0092, sorry to hear that you have faced this issue. 

Please note, the login page comes from WooCommerce. Hence it should not behave separately when a vendor is logging in, as the vendor is also a user of that site. 

Can you please do a small test.  Disable all the plugin except WooCommerce and WC Marketplace for testing purposes and check again. If the issue still exists, please switch to some default theme like Twenty Sixteen and check again.

Let us know the result so we can help you out further.
