### ISSUE TITLE
Manual Refund from vendor not working

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#351]
- Goto Vendor Dashboard >> Order section
- Refund an order manually
- You can see, the screen is freeze 
https://www.loom.com/share/d55e8fc37fa749dfa66e1263b8c1608d

**Comment by cool-raju** [comment]
@moumitahalder This issue has fixed in our 3.5.2 version. So m close this issue.
