### ISSUE TITLE
Key Performance exclude data

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#354]
1. Failed/ Cancelled/ Refunded orders need to be excluded from any calculation in the vendor dashboard 
key performance & Stats /reports Overview) and from the backend reports (WCMp Reports -> Net sales, Product sales, etc.)

2. Banking overview: The refund commission entry needs to include the order number info. Sometimes it is showing commission id / transaction id. 
I think it will be better for the vendor to have either order ID/Commission ID

**Comment by Beats24-7** [comment]
Additional information for 
2. Banking overview:  Cancelled orders need to generate a similar entry like refunded orders including a debit value with the amount of the commission. E.g: “Order cancelled #xyz – Commission #xyz” – Debit 9.95$. If this entry isn't added the balance calculation in your table will be wrong.
