### ISSUE TITLE
Refund module enhancement 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#366]
https://wc-marketplace.com/support-forum/topic/refund-new-function-bug/

**Comment by moumitahalder** [comment]
@cool-raju Please check these issues :
- The Refund Accepted, Rejected is not getting added as an order not under suborder and parent order
- Please modify the email Subject line and heading, when you are sending the refund rejected/canceled mail
We can't distinguish the emails from each other
- I am getting two emails for same refund status 
![download](https://user-images.githubusercontent.com/28754174/86323770-0d55e400-bc5b-11ea-9459-aafaee3324cf.png)

**Comment by cool-raju** [comment]
Hi @moumitahalder 
I have tested it in my end. Here is the video https://www.loom.com/share/32e329226b3048329ebf108cd1c6d4d4
Didn't face any such issue here. Maybe you have added more than one email server plugin. So that issues occur. Can you please check again.

**Comment by moumitahalder** [comment]
Okay.

@cool-raju What about the other two points

**Comment by cool-raju** [comment]
@moumitahalder I have added a new pull request with changes. It is also marged in core..
