### ISSUE TITLE
Add hook for implementing other map  providers

### ISSUE THREAD

**Issue by alexjavier15** [wcmarketplace/dc-woocommerce-multi-vendor#368]
It could be nice to hook the geolocation code so developpers can implement support for map providers different from Google Maps.

https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/blob/27c9b3d30f5d75409faba02a752f7067e3268d27/templates/vendor-dashboard/shop-front.php#L252-L259

**Comment by cool-raju** [comment]
mapbox feature added
