### ISSUE TITLE
Vendor Shop Description Image issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#387]
* Recreate the issue*
- add an image to a Storefront Description (to the area where you can have text and images), it’s shown properly as full-size. 
- When I view this vendor on the website, the image becomes very tiny. 

Src : https://wc-marketplace.com/support-forum/topic/store-settings-image-weird-bug/#post-98136

**Comment by cool-raju** [comment]
Already fixed this in the previous version @moumitahalder
