### ISSUE TITLE
Commission withdraw error

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#397]
Warning: A non-numeric value encountered in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-post-transaction.php on line 326

Warning: Cannot modify header information - headers already sent by (output started at /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-post-transaction.php:322) in /home/wcmpdemos/public_html/moumita/wp-includes/pluggable.php on line 1281

Warning: Cannot modify header information - headers already sent by (output started at /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-post-transaction.php:322) in /home/wcmpdemos/public_html/moumita/wp-includes/pluggable.php on line 1284

**Comment by lamda** [comment]
This is still an issue for me (3.5.13).
