### ISSUE TITLE
Display Unit of weight and dimension in Add Product Page

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#425]
- WooCommerce shows the Unit of weight and dimension in Add Product Page: https://prnt.sc/tnsgg0 as per the settings : https://prnt.sc/tnsjw5

- The same should be displayed in vendor's end too : https://prnt.sc/tnskfb

**Comment by cool-raju** [comment]
Already fixed
