### ISSUE TITLE
wcmp-emails-vendor-orders-stats-report.php /  missing attachment in email

### ISSUE THREAD

**Issue by aurel90** [wcmarketplace/dc-woocommerce-multi-vendor#426]
Hi,

When Vendors receiving their weekly or monthly report (“Vendor orders stats report”) via e-mail, there is no csv attachached with their sales t the end of the e-mail is just mentioned “There is no stats report available.”

I see in code they have connecting with $report but in the email I didn’t recieve the csv attachment about report.

The code in **wcmp-email-vendor-orders-stats-report.php**:

`<?php if($attachments && count($attachments) > 0 && $report_data[‘order_data’] && count($report_data[‘order_data’]) > 0 ){ ?>
`
`<p><?php echo __( 'Please find your report attachment', 'dc-woocommerce-multi-vendor' ); ?></p>
`
`<?php }else{ ?>
`
`<p><?php echo __( 'There is no stats report available.', 'dc-woocommerce-multi-vendor' ); ?></p>  
`
`<?php } ?>
`
`<?php do_action( 'wcmp_email_footer' ); ?>
`

Someone have any idea how can I fix this issue?I need attachment from $report but now I didn't recieve it?

Thanks!

**Comment by moumitahalder** [comment]
@aurel90 thanks for reporting this.

We will fix this in our next update. They will add the fix in the GitHub soon.

**Comment by aurel90** [comment]
@moumitahalder thanks for answer!

**Comment by aurel90** [comment]
Thank you guys!! 👍

**Comment by purnendudash** [comment]
You are welcome @aurel90
