### ISSUE TITLE
On failed payment vendor order status is not set to processing

### ISSUE THREAD

**Issue by jsakas** [wcmarketplace/dc-woocommerce-multi-vendor#437]
When a payment fails, the parent order is set to `failed`, then if the payment goes through, the parent order is updated to `processing` but the child order does not update to `processing` and remains as `failed`. 

I tracked down the issue to this line: https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/blob/master/classes/class-wcmp-order.php#L738

It's not clear why the early return is needed, or what potential regressions removing this conditional statement would have. Can the WCMp team please provide any insights?

**Comment by sumit-singh-hash** [comment]
Hi @jsakas jsakas, I have tried to create the failed order using stripe and paypal sandbox but somehow i am unable to create the failder order, So can you guide us with a short video regarding the same issue.
