### ISSUE TITLE
calculate shipping vendor id incorrectly set to 1 on multi vendor orders

### ISSUE THREAD

**Issue by jsakas** [wcmarketplace/dc-woocommerce-multi-vendor#440]
When an order has multiple vendors, the calculate shipping argument `$package` does not have the `$package['vendor_id']` set properly, and it comes through as `1`, not the vendor id.

I found a work around is to use `$package['user']['ID']` but wanted to report this inconsistency, I think the vendor_id should be set correctly and this is a bug

**Comment by jsakas** [comment]
Digging further, I found that this issue causes "no shipping methods" message to appear when you have multiple vendors in an order who are using either free shipping or flat rate shipping. This line: https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/blob/master/classes/shipping-gateways/class-wcmp-shipping-method.php#L187

**Comment by cool-raju** [comment]
Hi @jsakas ..
in line no 189 there is a checking.If there is no vendor id then it will return.Can you please explain with a video, that when you get "no shipping methods" this massage.So that we can recreate it in our end
