### ISSUE TITLE
It is same as Dokan Multi-vendor?

### ISSUE THREAD

**Issue by williamgh2019** [wcmarketplace/dc-woocommerce-multi-vendor#445]

**Comment by moumitahalder** [comment]
Hi @williamgh2019 thanks for getting in touch with us.

Yes, using WC Marketplace (https://wordpress.org/plugins/dc-woocommerce-multi-vendor/) you can create your own multi-vendor site, where vendors will have 
- their own Dashboard
- Product management
- Order management
- Inventory management.
- Vendor announcement module

Vendors can register themselves through registration form as well as can be manually added by the admin

Admin can earn a commission from each sale. 

Our feature list will be able to help you out better - https://wc-marketplace.com/features/

For further help, please do check our demo site: http://wcmpdemos.com/all-in-one-demo/my-account


Besides, we have paid and free addons - https://wc-marketplace.com/addons/
That will enhance your marketplace further and will provide more features.

If you have any further queries or need any specific flow, please do let us know. We are here to help you out always.
