### ISSUE TITLE
Chosen List not working anywhere in WCMP after WordPress 5.5

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#462]
- https://wc-marketplace.com/support-forum/topic/cannot-choose-vendor-list-search-not-working/

**Comment by joshchretien** [comment]
Any updates to this? We are still having issues assigning products to vendors. Even utilizing the jquery Migrate helper is only a temporary fix.

**Comment by moumitahalder** [comment]
@joshchretien , our team will give you an update within Monday or Tuesday at max.
