### ISSUE TITLE
Product wise commission for variable product not working

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#511]
The Product-wise commission for the variable product is not working. It is taking global commission. 
![Edit-product-‹-WCMp-Demo-—-WordPress](https://user-images.githubusercontent.com/28754174/93100305-a4610280-f6c6-11ea-88ae-f6122701bc7a.png)

src : https://wc-marketplace.com/support-forum/topic/commission-not-calculating-correctly-2/#post-104226

**Comment by cool-raju** [comment]
For variable products, you must add a commission in each and every variation. Because variable product depends on the variation.
You can add commission in variable products from here https://prnt.sc/uoaksp. There is no bug
