### ISSUE TITLE
All products page is broken with flatsome theme

### ISSUE THREAD

**Issue by sheensol** [wcmarketplace/dc-woocommerce-multi-vendor#54]
Hi,

i am getting this below message, kindly help me in this regard

![image](https://user-images.githubusercontent.com/983290/54868299-eef10f80-4dac-11e9-94b9-8d2cecce3c56.png)

console windows
![image](https://user-images.githubusercontent.com/983290/54868313-121bbf00-4dad-11e9-89a3-6004ccc7f8ae.png)

![image](https://user-images.githubusercontent.com/983290/54868315-19db6380-4dad-11e9-8a23-0b440ce1d89f.png)

**Comment by moumitahalder** [comment]
Hi @sheensol, sorry to hear that.

Can you please get in touch with us over our forum, so we can help : https://wc-marketplace.com/support-forum
