### ISSUE TITLE
Current SPlit Order Feature doesnt make any sense...

### ISSUE THREAD

**Issue by erikdemarco** [wcmarketplace/dc-woocommerce-multi-vendor#55]
I tried the 'dev' branch. there's couple things I need to ask:

1. why there is no vendor singup link in myaccount page?

2. why not hiding parent order from customer order list? it doesnt make any sense showing this parent order to them.

3. why for new order using 'bank transfer', the parent order have 'on hold' status, child order have 'pending' status? parent and child order status should be synced when payment gateway update the parent order!.

4.why order notes is not separated between vendors? because the inputed order notes can be seen by both party

**Comment by moumitahalder** [comment]
@erikdemarco, The vendor registration form is a separate page, hence the vendor needs to access that page and fill up the data to be the vendor. As you can see here - http://demo.dualcube.com/wordpress/wp1013/vendor-registration/

So, what you can do is add a custom button in my account page called "Register as Vendor" and then direct the user to the vendor registration page.

We will get back to your other queries.

**Comment by khokandc** [comment]
@erikdemarco, thanks for your above points. As you know its still in development version, so we don’t recommend you run it on a production site. And we created this branch only for testing purpose and like you all our user inputs will definitely help us to fixes all the major minor issues. Our inputs for your above queries are as follows - 

2. Yes parents order is showings just because if a order contains some admin products as well as vendors products. That's why we shown both order details. As per points you are rights we needs to do more fiiterization to show orders in customer section.

3. Yes we also faced this issues for bank process or on-hold status.

4. Admin should have all the transparency regarding orders as well as vendors. Anyway, we got your points and will definitely add some customisation ( hooks / filters ) here.

Please let me know if you have some others issues, queries or enhancements.

**Comment by erikdemarco** [comment]
2. 'because if a order contains some admin products as well as vendors products' then i think its better to create a child order for admin item? i think the point of having parent order is just to make it easy for payment gateway to update the order status, so all child order status get synced with parent order?

3. why dont just hook it to 'woocommerce_order_status_changed' so whenever parent order status changed, we should also update all the child order status.

4. if vendor1 is selling 'vegetable' and vendor2 is selling 'smartphone'. and the customer add a note 'please cook it before send'. Because 2 vendors can read the same note. Vendor2 will cook the smartphone?

**Comment by itzmekhokan** [comment]
@erikdemarco 
2. 'just to make it easy for payment gateway to update the order status' its not just updating order status, there is others many things thats depends on parent order.
3. 'why dont just hook it to 'woocommerce_order_status_changed', if you check our code then you can definately find that we used exactly same `woocommerce_order_status_changed` filter to synced orders
4. As per you customer add notes section provided by woocommerce on checkout for a combine order. And as per customer'a order note its not possible to differentiate for which product the order note is. Thats why the common message is shown to all related orders.

**Comment by khokandc** [comment]
@erikdemarco 
2. 'just to make it easy for payment gateway to update the order status' its not just updating order status, there is others many things thats depends on parent order.
3. 'why dont just hook it to 'woocommerce_order_status_changed', if you check our code then you can definately find that we used exactly same `woocommerce_order_status_changed` filter to synced orders
4. As per you customer add notes section provided by woocommerce on checkout for a combine order. And as per customer'a order note its not possible to differentiate for which product the order note is. Thats why the common message is shown to all related orders.

**Comment by erikdemarco** [comment]
2. May I know the reason you choose to 'split order' so vendor can edit their own order? Why not make like "woocommerce product vendors" do. they keep the order unchanged and unsplitted, but they add new field 'fulfilment_status' in the order meta, so each vendor can edit their own 'fulfilment_status'. Its a clean way to make sure it will be compatible with the future woocommerce update.
4. what i do now is make a 'note' for "per product" order instead 'per order_id'

**Comment by moumitahalder** [comment]
@erikdemarco, thanks for sharing the suggestions.

We will look into this.

**Comment by moumitahalder** [comment]
Every plugin has some unique features with structural coding standards and has some planning or goals, the way its implemented with every version. We also have some further marketplace enhancements based on this with some well-known features like affiliation, live order tracking etc. Keeping all those in our planning, WCMp v3.4.0 is our initial steps towards our goals. I hope we are able to clear some of our ideas to you.
