### ISSUE TITLE
Error calculating commissions

### ISSUE THREAD

**Issue by tompalmer** [wcmarketplace/dc-woocommerce-multi-vendor#56]
I use Woocommerce points and rewards, an the "share coupon cost" feature doesn't work because their system isn't based on coupons.

**Comment by moumitahalder** [comment]
Hi @tompalmer, thanks for the query. 

It seems the Point and reward plugin is not compatible with WC marketplace, that is why "share coupon cost" will not work on this.

However, you have to do custom code and make them compatible with WC marketplace. Let us know if you need reference of hook/filter.

**Comment by Matthieuhal** [comment]
@tompalmer I am using Points&rewards along with wpaffiliates and didn’t identify any incompatibility (so far) between wcmp and Points&rewards.
Could you please give more details about this incompatibility ?

**Comment by tompalmer** [comment]
Well it’s that simple

If someone buys something at 10 and has a 1 reduction.
My vendor get’s his commission on 10, as if « share coupon cost » wasn’t selected.

I’m not familiar with code enough to solve the problem myself unfirtunately

**Comment by tompalmer** [comment]
So, any solution ?

**Comment by moumitahalder** [comment]
@tompalmer as we haven't worked with Point and Reward system, hence we need some additional information. 

@Matthieuhal, did you disable the option "Share Coupon Discount"  (see this screenshot - https://prnt.sc/nci8hd) and calculated the commission?

**Comment by tompalmer** [comment]
Follow up, still won’t work because points are not used as a coupon, how could I change it ?

**Comment by tompalmer** [comment]
I got this from the plug in author :

Description:
You will have to know PHP in order to make the changes, but when you do do not make changes directly to hostplugin functions. Look at the php files inside includes folder, to see how hostplugin use woocommerce & wordpress hooks and filters.

Please also take a look at this article:

https://docs.woocommerce.com/document/create-a-coupon-programatically/

**Comment by itzmekhokan** [comment]
As our plugin is not compatible with Woocommerce points and reward and as per above shared link is basically a custom code snippet to create coupon. So, it needs some depth customization to achieve your works.
For now we are closing this issues.
