### ISSUE TITLE
Woocommerece report not showing refund amount when WCMp is installed

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#625]
Thread link : https://wc-marketplace.com/support-forum/topic/re-refund-are-not-shoing/#post-113065

Recreate the issue : refund a order and check woocommerece report >> refund section>> amount is 0.00.
Now uninstall wcmp and check the woocommerece report >> refund section >> amount can be seen.

Actual outcome : the refund section of woocommerece report should show the refund amount.

Video link : https://www.loom.com/share/fb11a626d0f64963a5db0d4892dbb903

**Comment by moumitahalder** [comment]
@cool-raju please check this urgently
