### ISSUE TITLE
Product tag takes any option typed there in the vendor dashboard

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#632]
Recreate the issue : go to admin dashboard, add a product tag from product page no issue found. Now, go to vendor dashboard>> select a product >> edit it>> add product tag, you will see it takes all the options typed there which are not included in the product tags.

Actual outcome : it should work as it works on admin dashboard.

Thread link :  https://wc-marketplace.com/support-forum/topic/vendor-tags-disappear/#post-113286

Video link : https://www.loom.com/share/64cf6a79c9964749819a1901067bf290

**Comment by cool-raju** [comment]
@srutakirty.There is no such issue. Please check woocommerce product tag. From there you can also add any name tag. Please share woocommerce tag video with the client. We are following the same thing. Here is the screenshot https://prnt.sc/wlqyqh
