### ISSUE TITLE
Incorrect product count for Vendors on admin and vendor end

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#635]
Recreate the issue : issue 1 : create 3 new vendors from admin end. Assign products to first 2 vendors and to the third vendor assign no products. Now check on admin dashboard >> WCMp >> vendors >> no of products will not match to the actual number of products. Now check for the vendor to whom no products are assigned, it will also give a particular number of products. Now check from vendor end, the number of products published will not match to the number of products it shows as published on vendor dashboard >> all products.

Issue 2 : the trash, pending, draft category under all products in vendor dashboard (https://prnt.sc/x4eyah) also shows the wrong number of products as you can see here (https://prnt.sc/x4fiw5)

Actual outcome : The number of products seen under vendors in the admin end should match to the number of products seen under all product in vendor dashboard

Video link : https://www.loom.com/share/427cc5ce5d9245178c597a98871ff3df

Thread link : https://wc-marketplace.com/support-forum/topic/incorrect-product-count-for-vendors/#post-113790

**Comment by abhirup97** [comment]
Wrong number of product showing from admin end>> WCMp >> vendors  product column
SRC =  https://wc-marketplace.com/support-forum/topic/issue-on-vendor-view-with-latest-update/#post-114047

**Comment by blueprin4** [comment]
This did not fix the issue it just masked it.  It removed the added incremental product number, but when clicking on the number of products the results are blank. To replicate add committed code.  Then goto wcmp->vendor. Click a vendor with products and results will return empty.
