### ISSUE TITLE
wcmp-report-section-not-working-correctly

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#636]
https://wc-marketplace.com/support-forum/topic/wcmp-report-section-not-working-correctly/#post-114112

is there a way to show commissions for all vendors in a more compact way or generate a monthly payout csv file? It isn’t possible to see all commissions for all vendors on one screen and your list is very bulky if you have many vendors: http://www.prnt.sc/x8c5u8
With EDD for example it was possible to generate a clean and easy table (or payout csv file) so you can overview the commissions for a whole month: http://www.prnt.sc/x8cobv

**Comment by cool-raju** [comment]
third party plugin conflict
