### ISSUE TITLE
woocommerece report showing 2x times the total order

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#644]
Recreate the issue 1 : place a new order eg:100$ and in the gross amount of woocommerece report 200$ is shown.

Actual outcome 1 : the gross amount should come as 100$

Video link 1 : https://www.loom.com/share/7e54acf9a5f348789642a285713d98da

Recreate the issue 2 : if the item in the order placed = 1 then in the woocommerece report order placed = 2, item purchased = 2

Actual outcome 2 : the outcome should be order placed  = 1, item purchased = 1.

Video link 2 : https://www.loom.com/share/3d4c85dcf68c4b5887119c1374709bd3

Thread link : https://wc-marketplace.com/support-forum/topic/re-refund-are-not-shoing/#post-114718
https://wc-marketplace.com/support-forum/topic/woocommerce-report-showing-double-earnings/#post-114717

**Comment by alento-group** [comment]
Hello,

I just installed the updated plugin and it fixes half of the problem.  Both the price and number of orders is doubled.  The price is fixed but the number of orders still shows double.
