### ISSUE TITLE
Free digital product with a zero price and commissions

### ISSUE THREAD

**Issue by StefanPeev** [wcmarketplace/dc-woocommerce-multi-vendor#670]
If the vendor offers a free digital product with a zero price and somebody download his product, it is included in Commissions section as an unpaid commission. So admin need to change the unpaid zero commission to paid zero commission. Is it possible this operation to be automated and every product with a zero value to be always checked as paid in Commission section?

**Comment by srutakirty** [comment]
Hello @StefanPeev ,

May i know if you have kept the commision field empty? Can you please share a detailed steps on how to recreate the issue at our end and we can help you more efficiently.

**Comment by StefanPeev** [comment]
I tried both the ways - I kept the commision field empty and I also inputed zero in the commision field. The final result is one and the same in both cases. The order goes to field COMMISION and stays there as upaid with a value of 0.

**Comment by moumitahalder** [comment]
@StefanPeev, by default we don't mark any commission as paid (whether the value is 0).

However, you can do a custom code and set all the commissions as paid if the commission value is 0.
