### ISSUE TITLE
Styling Bugs (CSS)

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#677]
Please note that I'm testing **v3.5.18** on **WP 5.6.1** and I've noticed some styling issues mostly related to the alignment/centering of the elements on page as you can see in the next screenshots:
![style_bugs](https://user-images.githubusercontent.com/3336728/108608541-3a186080-73d0-11eb-8f62-1fc2d9517ed2.png)

- ### **Mobile view:**

![152348207_179481540637888_7799601304230412668_n](https://user-images.githubusercontent.com/3336728/108608546-4997a980-73d0-11eb-8b7f-a2db36dfdd0f.jpg)

![152568358_856439244926421_2501984933032343114_n](https://user-images.githubusercontent.com/3336728/108608548-4bfa0380-73d0-11eb-9573-a91473e9e8e9.jpg)

- ### **Can't click on the menu items on mobile as it's grayed out:**

![152221082_445642066867480_8690070150222021386_n](https://user-images.githubusercontent.com/3336728/108608558-5b794c80-73d0-11eb-8936-35a5811fc03f.jpg)

**Comment by moumitahalder** [comment]
@Tangol, thanks for reporting this issue, we will fix this in our next update.

**Comment by moumitahalder** [comment]
@abhirup97 please check the issue no 1

**Comment by moumitahalder** [comment]
We have fixed this issue in our latest update i.e. 3.6
