### ISSUE TITLE
Wp-Admin Reports Section Issues

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#679]
1. When you click on **Pending Vendors** you get redirected to the **To-do** page. It should send you to: 
`/wp-admin/admin.php?page=vendors&role=pending`
2. When you click on **Awaiting Products** you get redirected to the **To-do** page.
3. When you click on **Awaiting Withdrawals** you get redirected to the **To-do** page.

localhost
Apache 2.4
PHP 7.2.34
MySQL 5.6.48
WCMp 3.5.18
WP 5.6.1

**Comment by moumitahalder** [comment]
@Tangol, the reason we direct the admin to the To-Do list page because from there he/she can approve/reject vendors, their product https://prnt.sc/103sukg

However, if you want, we can provide hook/filters, so the user can manipulate that as per their need

**Comment by Tangol** [comment]
@moumitahalder I thought it was a bug.
Thanks for the clarification.

Closing it.
