### ISSUE TITLE
Banking Overriew Issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#68]
If commission is paid, the amount is not getting added in the banking overview.
Commission payment - https://prnt.sc/oz6f8f
Banking view :  https://prnt.sc/oz6fx0

**Comment by itzmekhokan** [comment]
@moumitahalder do a test with a new vendor with fresh ledger.

**Comment by moumitahalder** [comment]
I created new vendor access. Still, the issue exists: https://prnt.sc/ozy77c

**Comment by moumitahalder** [comment]
Please check this thread - https://wc-marketplace.com/support-forum/topic/bug-in-class-wcmp-ledger-php/
