### ISSUE TITLE
Custom Vendor Store Fields

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#680]
In most European countries, laws, regulations and payment providers require that all online businesses have to visibly display their company identification details (VAT/Tax number, [EUID](https://wtsklient.hu/en/2017/08/08/european-unique-identifier/), Bank IBAN etc.).
So in the **Vendor Registration>Vendor Store Fields** we need another custom **Textbox** field that can be used to make sure the vendor actually displays this info. It should be the same as the one in the vendor **Form Fields**.

Here's an [example](https://translate.google.com/translate?sl=ro&tl=en&u=https://www.emag.ro/sctlkpze/5866/v) of a 1 billion dollar marketplace from my country.
As you can see, they require that the vendor displays all his identification details on his profile page.

Also, all these information need to appear on the invoice received by the customer, so it needs to get linked to the **PDF Invoices** system.

**Comment by moumitahalder** [comment]
@Tangol, our addon WCMp PDF Invoice (https://wc-marketplace.com/product/wcmp-pdf-invoice/) lets the vendor add their GST/TAX Number. We do have code snippet for this : https://wc-marketplace.com/knowledgebase/wcmp-pdf-invoice-hooks-and-filters/

**Comment by Tangol** [comment]
@moumitahalder The PDF linking is only part of the story. 
The main point is related to the Vendor Store Fields which only has some predefined fields, and we should also have a custom **Textbox** field here.

![fields](https://user-images.githubusercontent.com/3336728/108718145-cfc60400-7526-11eb-82e7-dbbd371c54a3.png)

**Comment by moumitahalder** [comment]
You can use our custom tab to customize the form as per your need : https://prnt.sc/10gukyn
