### ISSUE TITLE
Product Categories/Search on Vendor Profile Page

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#681]
Most Marketplace Plugins, show on the Vendor profile page, the product categories in which the vendor has products listed and a search form. As you can see, [WCMp](http://wcmpdemos.com/all-in-one-demo/vendor/cacchiolini/) is the only one that is missing this feature.
Here are some demos from other competitors: [1](https://wcfmmp.wcfmdemos.com/store/demo-vendor/?v=dc22bee690b7), [2](https://electromarketplace.dokandemo.com/store/admin/), [3](https://demo.wcvendors.com/j7ipeqo2183mgt4/vendors/vendor-two-store/)

This is a very important feature for vendors, as it lets them have fully featured stores on our marketplace.
Again, an [example](https://translate.google.com/translate?sl=ro&tl=en&u=https://www.emag.ro/sctlkpze/5866/v) of how a huge marketplace does it.

**Comment by moumitahalder** [comment]
@Tangol, we have a widget called WCMp Vendor's Product Widget (https://prnt.sc/103k61y), this widget display all the categories in which the vendor has the products.

**Comment by Tangol** [comment]
@moumitahalder yes, you are right, I didn't notice it.
Sorry about that!

Closing it.
