### ISSUE TITLE
Packing Slip

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#684]
In **v3.5.18** the **Packing Slip** is missing the customer **phone number**.

Keep in mind the the email is not necessary to appear on the packing slip, only the phone number.

**Comment by moumitahalder** [comment]
@Tangol, packing slip feature is added via our addon WCMp PDF Invoice : https://wc-marketplace.com/product/wcmp-pdf-invoice/
