### ISSUE TITLE
Invoice missing fields

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#685]
Please note in some countries it's required by law that the **Invoices** also contain the following:

- Customer Email
- Customer Phone
- Vendor Email
- Vendor Phone
- Vendor Custom Fields (related to https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/issues/680)

**Comment by moumitahalder** [comment]
As Invoice features comes with our addon WCMp PDF Invoice (https://wc-marketplace.com/product/wcmp-pdf-invoice/), we will add this option in our next update of PDF Invoice
