### ISSUE TITLE
Download Invoices Issue

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#686]
I've noticed that all downloadable PDF documents open in the same window, which is so bad for usability as you have to go back and reload the **Orders** page, every time you work with PDF's.

![download](https://user-images.githubusercontent.com/3336728/108625372-4691cd00-7453-11eb-9042-74a7c06b71bf.png)

So `target="_blank"` should be added to all PDF download buttons and also to the **View** order button, in order to open them in new tabs.

**PS:** The correct extension display is **PDF** not **Pdf**.

**Comment by moumitahalder** [comment]
We have settings for our addon WCMp PDF Invoice, that lets the admin decide whether he will download the invoice or open this in another tab : https://prnt.sc/103vz5c

**Comment by Tangol** [comment]
Sorry @moumitahalder but this is still bugged, as you can see in the following recording:
https://drive.google.com/file/d/1rbl4ZiawAHTzlDhQcacCjGyqGLfu2RWy/view

When you click on the invoice it doesn't get downloaded, it opens in the same window.
So please re-open the report.
Thanks!
