### ISSUE TITLE
Code Static Analysis Tool

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#687]
With the abundance of functionality that WCMp offers, we need to be 100% sure that no loopholes appear in the code.
In order to prevent this, I suggest that you guys add [CODACY](https://www.codacy.com/) to this repository, as it's free for open source and helps in developing clean code by pointing out issues that can be missed by developers.

It's the "eye in the sky" 👍

**Comment by cool-raju** [comment]
Hi @Tangol 
Thank you so much. We will definately add this in our repository.
