### ISSUE TITLE
Reports Overview issue

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#688]
Please note that the admin **Reports Overview** `/wp-admin/admin.php?page=reports&tab=overview` date selector dropdown doesn't work.
When you click on the custom date, nothing happens.

Also, you get **Overview** twice, one for the Admin and the other for the Sales. In order to avoid confusion, the one for the sales should be renamed to **Sales Overview**.

![overview](https://user-images.githubusercontent.com/3336728/108638941-7ca66f80-749a-11eb-9cc5-7ce19f543137.png)

**Comment by moumitahalder** [comment]
@Tangol, this will be fixed in our next update.
