### ISSUE TITLE
Admin Reports section breaks the responsive menu

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#689]
Please note that viewing the **Reports** section on mobile **/wp-admin/admin.php?page=reports** breaks the hamburger side menu.
You click on it and it doesn't open anymore.
You can test here http://wcmpdemos.com/all-in-one-demo/wp-admin/admin.php?page=reports

![menu](https://user-images.githubusercontent.com/3336728/108639187-ea9f6680-749b-11eb-88cf-009f14c102c4.png)

**Comment by cool-raju** [comment]
Hi @Tangol 
WordPress backend is completely coming from WordPress code. The left side toggle is included in this. We have also checked in our end and it's working perfectly.

**Comment by Tangol** [comment]
Weird, it seems to be working now on WP 5.6.2.

Closing it. Thanks!
