### ISSUE TITLE
Missing separator between the stock options

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#690]
As you can see in the screenshot, the 3 options appear without any space/separator between them.
It happens also at the Advanced Report and Enquiry Settings.

![stock](https://user-images.githubusercontent.com/3336728/108639334-a19be200-749c-11eb-87bc-6c298bccde5a.png)

![report](https://user-images.githubusercontent.com/3336728/108640116-8df27a80-74a0-11eb-923e-fc7dd6472eeb.png)

![enq](https://user-images.githubusercontent.com/3336728/108641849-3e18b100-74aa-11eb-8988-2ecedeefcdf7.png)

**Comment by moumitahalder** [comment]
@Tangol, these issues are related to our addons, we will fix them in those addons.
