### ISSUE TITLE
Logical Rearrangement of the Dashboard Menu

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#691]
At the moment the Dashboard menu options are arranged a bit chaotical.
It should be arranged according to the importance (most used elements first).
The way I see it is:

- Dashboard
- Product Manager
- Orders
- Coupons
- Catalog Enquiry
- Subscriptions
- Bookings
- Payments
- Stats/Reports
- Staff Management
- Store Settings
- Tools
- Knowledge Base

![menu](https://user-images.githubusercontent.com/3336728/108639713-8e8a1180-749e-11eb-94a0-f1c60afb3d77.png)

**Comment by moumitahalder** [comment]
Thanks for sharing your view, we will add them in our corresponding addons.
