### ISSUE TITLE
Dashboard - Advanced Report long/bad query?

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#693]
Please note that when you go to **Dashboard>Stats/Reports>Advanced Report**, the page takes exactly 35 seconds to load, which means that there's a bad query somewhere.
This is happening on a test system with virtually 0 traffic. 
Now imagine a hugely popular store with hundreds of visitors and vendors.
If multiple vendors will try to view/generate the Advanced Reports at the same time, will break the entire site.

You can check here: http://wcmpdemos.com/all-in-one-demo/dashboard/advanced-report/

As more performance improvements are needed, also have a look here:
https://wc-marketplace.com/support-forum/topic/wcmp-is-using-too-much-memory-wordpress-out-of-memory/

**PS:** This will help: https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/issues/687

**Comment by moumitahalder** [comment]
@Tangol, this is related to our addon WCMp Advanced Frontend Report. We will look into this.
