### ISSUE TITLE
English Corrections

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#695]
I've found some English mistakes as it follows:

- At **Add Staff**
Edit Publish Coupons should be Edit **Published** Coupons
Delete Publish Coupons should be Delete **Published** Coupons

![staff](https://user-images.githubusercontent.com/3336728/108642646-3f98a800-74af-11eb-9c57-9ea78a77105e.png)

- At `/wp-admin/admin.php?page=wcmp-setting-admin&tab=general&tab_section=general`
The highlighted text should be:
**Advanced** Marketplace Product Listing is a well known e-commerce product listing where you **cannot change** the options like Categories, GTIN, **once chosen**. By disabling you can override it.

Also the correct wording is **Advanced** not Advance.
![advance](https://user-images.githubusercontent.com/3336728/108642870-6dcab780-74b0-11eb-85bf-876ec7a39537.png)

**Comment by moumitahalder** [comment]
@abhirup97 please check the 2nd scrrenshot.
