### ISSUE TITLE
Vendor Products Q&As

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#697]
In the Vendor Products Q&As, the **Products** in the list should be clickable and should open in a new tab.
This improves the usability and makes it easier to see what the customer is talking about.

![product](https://user-images.githubusercontent.com/3336728/108643669-3827cd80-74b4-11eb-83b9-01dea4d9e448.png)

**Comment by moumitahalder** [comment]
@Tangol, we will add this in our next update.
