### ISSUE TITLE
Adding a product - unclickable search results

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#698]
When you search to see if a product you want to add exists, you are presented with a list of existing products.
The problem is that you can't click on the product in the list and see it.
So the product name should be clickable and should open in a new tab.

![addproduct](https://user-images.githubusercontent.com/3336728/108643805-cf8d2080-74b4-11eb-8181-6395bdc4b835.png)

**Comment by moumitahalder** [comment]
@Tangol, thanks for the suggestion, We will add this in our next update.
