### ISSUE TITLE
Product name link redirect to backend product page on wcmp vendor dashboard order details page

### ISSUE THREAD

**Issue by cool-raju** [wcmarketplace/dc-woocommerce-multi-vendor#70]
**Describe the issue.**
I have some vendor orders.When i'm going to edit those order then on that page i can see the product names are displayed.
When I click on that product names it will redirect me on vendor backend product page. 

![dashboard_order_product](https://user-images.githubusercontent.com/54469921/64128850-57b9ca80-cdd6-11e9-8a66-3289c21b744b.png)
![backend_page](https://user-images.githubusercontent.com/54469921/64128859-5dafab80-cdd6-11e9-81ca-bf42229c070f.png)
**To Reproduce**
Create a vendor order,then view it by clicking on the view icon.After that click on the product name.You can see it will redirect you to vendor backend product page.

**Expected behavior**
When i click on that product name ,it should be redirect to vendor dashboard product page.

**Comment by itzmekhokan** [comment]
Issue resolved #72
