### ISSUE TITLE
Extend KPI Period

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#701]
At the moment, the Dashboard shows the **store performance reports** for the last 7 and 30 days.
We should add another option for **90 days**, to better see how the store is doing over a longer period of time (e.g. you could be doing good in the last month, but comparing it to a 3 month period it's a disaster).

![KPI](https://user-images.githubusercontent.com/3336728/108726629-4e736f00-7530-11eb-820a-f263f9e3adf2.png)

**Comment by cool-raju** [comment]
can be done by using filter, template override
