### ISSUE TITLE
Customer Questions Direct Reply

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#705]
Please note that the AFM direct reply window has some issues (transparency) as you can see in the attached screenshot:

![reply](https://user-images.githubusercontent.com/3336728/108908968-9bd50680-762c-11eb-9ed9-6ebdb7f06f32.png)

**Comment by moumitahalder** [comment]
Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in /home/wcmpdemos/public_html/moumita/wp-includes/functions.php on line 5311

Notice: wpdb::prepare was called incorrectly. The query does not contain the correct number of placeholders (0) for the number of arguments passed (1). Please see Debugging in WordPress for more information. (This message was added in version 4.8.3.) in /home/wcmpdemos/public_html/moumita/wp-includes/functions.php on line 5311
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%d' at line 1]
SELECT * FROM wp_wcmp_cust_questions AS question INNER JOIN wp_wcmp_cust_answers AS answer ON question.ques_ID = answer.ques_ID WHERE product_ID = %d
