### ISSUE TITLE
Vendor dashboard not working through mobile phones

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#706]
Recreate the issue : inspect the page >> go to vendor dashboard >> click on any options like store front >> it remains on the same page.

Thread link : https://wc-marketplace.com/support-forum/topic/updates-causing-issues-with-vendor-dashboard/#post-116331

Video link : https://www.loom.com/share/2b058e2ff5d847e99215f3fd67244cd2

**Comment by Tangol** [comment]
Also reported here https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/issues/677
