### ISSUE TITLE
History section in vendor dashboard not working

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#714]
recreate the issue : go to vendor dashboard >> payment >> history >> click on the calendar section as you can see here (https://prnt.sc/10b6nt6) and the calendar section is not working 

Actual outcome: when the calendar section is clicked the calendar should be visible to let you select the dates as you can see here https://www.loom.com/share/3cb1e5ae21c54ff3b337b081fb49249b

Thread link : https://wc-marketplace.com/support-forum/topic/wcmp-is-using-too-much-memory-wordpress-out-of-memory/#post-116799

Video link : https://www.loom.com/share/c043a8a6d2d641b99915552d3e2384c9

**Comment by Tangol** [comment]
Related to this one https://github.com/wcmarketplace/dc-woocommerce-multi-vendor/issues/700
