### ISSUE TITLE
Order Status Bulk Change not working

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#742]
The vendor is not able to change order status via bulk mode
https://www.loom.com/share/acfef557e7294c07a4a973c494c4d2f9

**Comment by moumitahalder** [comment]
@cool-raju @abhirup97 please look into this as priority.

**Comment by MWaqasM** [comment]
Hi, 
The issue is also there while updating the status individually by-product - As shown in the following link
https://www.loom.com/share/d3ac96327f31434e9361d6ffa394563b

**Comment by cool-raju** [comment]
Hi @MWaqasM 
We didn't find an order status changed issue on the single order page. You might have a theme or plugin conflict on your end.

**Comment by MWaqasM** [comment]
> Hi @MWaqasM
> We didn't find an order status changed issue on the single order page. You might have a theme or plugin conflict on your end.

The single order page works every now and then, but it's not working consistently.
Furthermore, all the bulk order updates in the vendor dashboard are not working as well such as the orders, products, etc...
Following is an example:
https://www.loom.com/share/f463cbb47f684333a5b1eee5c21a2b38

I can provide you with the credentials to have a look as well.
Please fix this as soon as possible, as we already have one official vendor registered and is about to add their products.

Looking forward to your reply!
Waqas
