### ISSUE TITLE
Schedule button and cancel button in add product page of vendor dashboard not working

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#744]
Recreate the issue : go to vendor dashboard >> product manager >> add product >> go to general section where you add price of the product >> you will already see the date setting section for scheduled sale even before clicking on the schedule button as you can see here (https://prnt.sc/10k9e66) and the cancel button is also not working

Actual outcome: when you click on the schedule then you should see the sale price date section and when you click on cancel then the date setting section should disappear as you can see here https://www.loom.com/share/a1d1e81969834e1b88fed943bfb5412c

Issue thread : https://wc-marketplace.com/support-forum/topic/formatting-changes-on-front-end-products-tab/#post-117462

video link : https://www.loom.com/share/31b219b68efa470983ebe563ab004cd5

**Comment by cool-raju** [comment]
already created. Fixed already committed #739
