### ISSUE TITLE
share coupon discount not working properly

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#753]
Recreate the issue : go to admin dashboard >> WCMp >> settings >> payment >> uncheck this check box (https://prnt.sc/10n0vmy). Now create a coupon of fixed amount 100. Now place the order with the coupon.  Now check the commission section where the vendor should get a commission of 100 but you will see some other value.

Actual outcome : the vendor should bear the commission amount

Video link : https://www.loom.com/share/f03fb99593ee4726bc2d2446db586033

Thread link : https://wc-marketplace.com/support-forum/topic/commissions-for-vendors-are-not-properly-calculated-when-user-has-a-coupon-code/#post-117541

**Comment by cool-raju** [comment]
no such issue found

**Comment by cool-raju** [comment]
@srutakirty please check
