### ISSUE TITLE
Vendor not getting filtered by shipping in vendor list page

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#762]
Recreate the issue : go to vendor list page >> filter by shipping >> add a country, city, zipcode >> no result

Actual outcome : the vendor of corresponding country as per the filter applied should be visible.

Video link : https://www.loom.com/share/870c1acf28f745a48c1377687065ddbf

Thread link :  https://wc-marketplace.com/support-forum/topic/vendors-list-filtering/#post-117728

**Comment by srutakirty** [comment]
When you are filtering with ZIP code its showing vendors but when you are filtering with state its showing no vendors

Video link : https://www.loom.com/share/68a41259acb54b4ea2d49b52496c9ddb

**Comment by cool-raju** [comment]
@srutakirty no issue found
