### ISSUE TITLE
string missing from shipping page, order page on vendor dashboard

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/dc-woocommerce-multi-vendor#778]
Recreate the issue : go to loco >> wcmp plugin >> view string missing, download pdf string missing , duplicate string missing

Thread link: https://wc-marketplace.com/support-forum/topic/mangopay-registration-proof-missing-translation-issues/#post-118046

Screenshot : https://prnt.sc/10td76q   https://prnt.sc/10td7rn   https://prnt.sc/10td85z

**Comment by cool-raju** [comment]
1st screenshot is related to wcmp
