### ISSUE TITLE
Migration and Elementor Issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#779]
1. Parse error: syntax error, unexpected '$vendor_products' (T_VARIABLE) in /home/wcmpdemos/public_html/migration/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/migration/class-wcmp-dokan.php on line 56
2. Notice: Undefined index: reviews_number in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/widgets/class-wcmp-widget-vendor-review.php on line 80
3. Notice: Undefined index: title in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/widgets/class-wcmp-widget-vendor-quick-info.php on line 109
4. Notice: Undefined variable: description in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/templates/widget/quick-info.php on line 25

**Comment by moumitahalder** [comment]
5. Notice: Undefined index: title in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/widgets/class-wcmp-widget-vendor-info.php on line 80

**Comment by moumitahalder** [comment]
6. Notice: Undefined index: reviews_number in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix_follow-1/classes/widgets/class-wcmp-widget-vendor-review.php on line 8

**Comment by cool-raju** [comment]
all are previously added
