### ISSUE TITLE
Support for wordpress date format in WCMp dashboard pages.

### ISSUE THREAD

**Issue by sumit-singh-hash** [wcmarketplace/dc-woocommerce-multi-vendor#79]
Selected date format in wordpress setting is not reflecting to WCMp dashboard pages. It displays in a particular default date format.

**Comment by itzmekhokan** [comment]
@sumit-singh-hash , Can you share some screenshots which describes the above issue ID properly.

**Comment by sumit-singh-hash** [comment]
Initially vendor dashboard pages displays only particular date format.

screenshot link of wordpress seleted date format :- https://prnt.sc/p44hey
vendor dashboard :- https://prnt.sc/p44grw

but now vendor dashboard pages date format changes according to wordpress selected date format
vendor dashboard :- https://prnt.sc/p44jmx

**Comment by itzmekhokan** [comment]
@sumit-singh-hash, @moumitahalder  we do consider WordPress date format settings to display Date where it's display as normal view output ( render view ) but not in any datepicker filters. Even WordPress, WooCommerce itself doesn't consider this date format settings for date filters. We do follows the default date format `Y-m-d` for datepicker as WordPress, WooCommerce do. 
Please recheck.

**Comment by itzmekhokan** [comment]
@sumit-singh-hash @moumitahalder I'm closing this issue as I already discussed in my above comments.
