### ISSUE TITLE
bug on yith-auctionpro

### ISSUE THREAD

**Issue by genzo76** [wcmarketplace/dc-woocommerce-multi-vendor#791]
Into the file class-wcmp-afm-yith-auctionpro-integration.php at row: 58

 **$this->auctionable_product = wc_get_product( $this->id, array());**

The method return a WC_Product_Variable class, but the code want a WC_Product_Auction_Premium.

The problem is into **class-wc-product-factory.php** on this row:
**$product_type = $this->get_product_type($product_id);**

because return a wrong type, in this case have need to return "auction", but return the type of saved product.

**Comment by moumitahalder** [comment]
Hi @genzo76, I presume you are using WCMp Advance Frontend Manager. We have already fixed all the issues of the auction plugin and will be released in our next update. If you want to test the beta version, then please do create a thread in our forum (https://wc-marketplace.com/support-forum), so we can share this there.
