### ISSUE TITLE
AUtosave Flow

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#837]
One thing that is missing is revision/change management. When a vendor edits any content, such as a product or store settings, they can leave to another tab and it won’t ask them if they want to Save their changed data it first. Much like in normal WordPress if you edit a post, it will ask you if you want to save or leave since the content has been edited.

Our vendors have complained that they thought it autosaved and they’ll click out to another screen and they’ll end up losing it. Autosave is is a pretty common in applications these days, or at least a notification that the data has changed and asking them to save or ignore. Also, the word “Draft” in the product view doesn’t really make them realize that it’s a “Save” button.

If there’s anyway you could work in this feature to make it more user friendly, I’m sure the users would appreciate it so they don’t lose data they didn’t realize wasn’t being saved as they work.

https://wc-marketplace.com/support-forum/topic/need-check-in-place-when-data-is-edited/#post-114552

**Comment by cool-raju** [comment]
already explain in #969
