### ISSUE TITLE
name is not changing in profile management

### ISSUE THREAD

**Issue by S-Pal-tech** [wcmarketplace/dc-woocommerce-multi-vendor#873]
Recreate the issue: On vendor dashboard in the profile management option this part is changing without updating the password(https://prnt.sc/15dpehz) but the profile name is not changing (https://prnt.sc/15dpqta)

**Comment by abhirup97** [comment]
@S-Pal-tech we show the display name which is set from vendor backend (WCMp-> vendors ->edit vendor)
