### ISSUE TITLE
Undefined variable when viewing the vendor dashboard

### ISSUE THREAD

**Issue by alex-georgiou** [wcmarketplace/dc-woocommerce-multi-vendor#89]
Hello,

I am testing the plugin with debugging enabled, and I found a small bug that I thought I'd report. I get the following in the logs when I view the dashboard as a vendor:

`[13-Sep-2019 10:56:42 UTC] PHP Notice:  Undefined variable: value in /var/www/wordpress/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-ajax.php on line 3092`

The variable `$value` is used only once in `function wcmp_widget_vendor_product_sales_report()` and it is not defined anywhere.

This isn't causing me any problems at the moment but it might be worth looking into.

with regards

**Comment by itzmekhokan** [comment]
@alex-georgiou thanks for reporting. We fixed the issue.
