### ISSUE TITLE
when a new product is added a new coupon mail is send to the admin 

### ISSUE THREAD

**Issue by tan-hue** [wcmarketplace/dc-woocommerce-multi-vendor#915]
whenever the vendor adds a new product , instead of " New product added " mail  "  New coupon submitted " mail is  send  t the admin .
i have also attached a loom video to make the issue more clear 
https://www.loom.com/share/21b4b331a0c640498ca7ab36f6264cf7

**Comment by moumitahalder** [comment]
Create seperate mail for coupon
