### ISSUE TITLE
Publish Product is disabled, still vendor can publish product

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#924]
Recreate the issue
- Disable Publish Product via WCMp >> Settings >> Capability
- Goto Vendor dashboard and add a product
- You can see the product is published
- https://www.loom.com/share/d68956acbb584eaeb854bf2cfdf34967

**Comment by cool-raju** [comment]
After update capability settings, please refresh the page. then update you product.
