### ISSUE TITLE
New Commission %+fixed per vendor

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#934]
src : https://wc-marketplace.com/support-forum/topic/commission-type-age-fixed-per-transation-not-per-order/#post-126435

**Comment by victormattosvm** [comment]
Hello @cool-raju 
Thanks for the update. Just a question:

I'm using wcmp membership and as you did I can't override the vendor fee set in the membership settings. Just the single fee (% or fixed) set in wcmp general settings is being considered.

Is it possible to override it? 
I'd need to set vendor commission fee at order level.
