### ISSUE TITLE
the vendor location through map is not displayed on  the vendors list 

### ISSUE THREAD

**Issue by tan-hue** [wcmarketplace/dc-woocommerce-multi-vendor#946]
using Mapbox for showing the vendors location, but the vendor location is not getting displayed on the vendor's list also if we search the vendors by  the nearest location still is showing "0"

https://www.loom.com/share/0d9a0363395f4489b0dcbdc92cda5f3f

**Comment by cool-raju** [comment]
@tan-hue no such issue found. your site may block allow location due to an invalid SSL certificate. Check again
