### ISSUE TITLE
Issue with "Admin created coupon excluded" option of coupon

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#957]
Coupon discount-20%, Product Price-100$, Vendor commission-75%

1. Coupon created from admin end- keeping only “Share Coupon Discount” enabled and “Admin created coupon excluded” disabled..
https://prnt.sc/1v5wex3
Commission amount charged from vendor : https://prnt.sc/1v5x3qc
Vendor getting comission- 60$
 ============================================================================
2. Coupon created from admin end- keeping “Share Coupon Discount” disabled 
Comission amount charged from vendor:https://prnt.sc/1v5zfwc
Vendor getting comission amount 75$
============================================================================
 
3. Coupon created from admin end- keeping “Share Coupon Discount” enabled and “Admin  created coupon excluded” enabled
https://prnt.sc/1v5xiot
Comission amount charged from vendor:https://prnt.sc/1v5y619
Vendor getting comission 60$ instead of 75$  (ISSUE)

To recreate this issue, create a coupon from admin end,
Now enable “Share Coupon Discount” & “Admin created coupon excluded” enable.
As per our flow, when both the option are enabled and coupon is created from admin end, vendor should receive commission on 100$ product price, i.e, 75$.
But vendor is getting commission on 80$ (discounted price 100-20) product price, i.e, 60$.

**Comment by cool-raju** [comment]
enable ------------- vendor commission low     disabled -------------------- vendor commission high
