### ISSUE TITLE
Bulk delete – vendors

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#965]
when trying to delete multiple vendors at the same time using the BULK option.
It seems it does not work a returns a 0 code number.

https://www.loom.com/share/bbeed0d3ef0d4a64b2fe2cd09a85c6a1

src : https://wc-marketplace.com/support-forum/topic/bulk-delete-vendors/#post-129105

**Comment by cool-raju** [comment]
@moumitahalder di please test it with the latest version. I have already added a fix on last version
