### ISSUE TITLE
Display Announcement Content

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#971]
Display announcement content in mail

src: https://wc-marketplace.com/support-forum/topic/follow-up-emails/#post-129271

**Comment by cool-raju** [comment]
@vintagecodes 
where is the plain text code??
where is the definition of post_content??
Please don't share incomplete code. test it before share

**Comment by vintagecodes** [comment]
> @vintagecodes where is the plain text code?? where is the definition of post_content?? Please don't share incomplete code. test it before share

Edited.... Please check now its working

**Comment by cool-raju** [comment]
@vintagecodes you have to create a pull request. Normal added code on comment is not allowed.

**Comment by vintagecodes** [comment]
> @vintagecodes you have to create a pull request. Normal added code on comment is not allowed.

ok
