### ISSUE TITLE
commission issue after refund 

### ISSUE THREAD

**Issue by tan-hue** [wcmarketplace/dc-woocommerce-multi-vendor#976]
whenever a particular product is refunded the vendor commission is not calculated properly .

https://www.awesomescreenshot.com/video/5853806?key=a191ca00850f3b668a422d22b58d2b26

https://www.awesomescreenshot.com/video/5853901?key=0e3a2ef6369a3961d8de292be7a83153

the expected calculation : 
before refund : 

product price =100 shipping 20 with  10 percent admin commission . now , the  vendor commission ( 90+20 shipping ) =110.  gate charges  =( 14 which is correct )  . now ,  the net earning should be according to me 110-14 = 96 .

calculation before refund :  refunded 50 
70 after the refund  from the total product price , (50+20 shipping ) admin commission 10 percent of 50 = 5 , net vendor commission ( 50-5 = 45+20) = 65 , now  gateway charges =( 9 which is correct ) . now , the final commission the vendor should receive according to me ((((( 65-9 === 56))))

**Comment by cool-raju** [comment]
@tan-hue explain thoroughly. expected behaviour, current status etc
