### ISSUE TITLE
Shipping by country issue in admin end

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#986]
https://wc-marketplace.com/support-forum/topic/shipping-by-country/#post-130574

When shipping by country is selected in vendor end then all the add fields option are there: https://prnt.sc/1zngx10

But when shipping by country is selected in admin end then add fields option are not there: https://prnt.sc/1znh1b5

**Comment by cool-raju** [comment]
what is this???? In the frontend, you have open vendor end shipping and in the backend, you have open admin end woocommerce settings. You have to go individual vendor section for working.
Please test one more time

**Comment by cool-raju** [comment]
@moumitahalder di and @aditidualcube
