### ISSUE TITLE
Upload media files option not working

### ISSUE THREAD

**Issue by aditidualcube** [wcmarketplace/dc-woocommerce-multi-vendor#987]
WCMp> settings> capabilities > upload media files when enabled then vendor can upload media files in add product page. 

But when upload media files option is disabled then also vendors are getting the option to upload media files: https://www.loom.com/share/b0982bb50fc24c578aa10008bb5f6a36

**Comment by cool-raju** [comment]
check multiple times before creating an issue

**Comment by cool-raju** [comment]
No such issue

**Comment by cool-raju** [comment]
If you find any issue then share a video
